add KingSuper cert
PeggyJV/steward-registry pull request #43
Opened 2022-11-27 08:05 UTC by aditya-manit

2022-12-07 04:06 UTC, aditya-manit commented
@cbrit @EricBolten can someone please review this ?

2022-12-07 20:00 UTC, cbrit requested changes
Thank you for the PR! One small change needed is for the O (organization) field of your cert(s) to be changed from the default "Internet Widgits Pty Ltd":

```
depth=0 C = AU, ST = Some-State, O = Internet Widgits Pty Ltd, CN = sommelier-steward.kingsuper.services
```

Will also need to merge main as other PRs have been merged recently

2022-12-09 13:13 UTC, aditya-manit commented
Requested Changed Done, merge conflicts are also resolved.

2022-12-09 20:03 UTC, cbrit approved these changes

2022-12-09 20:03 UTC, merged